[package]
name = "try_words"
version = "0.1.0"
authors = ["Sebastian <Sebastian@Strobl.net>"]
edition = "2018"

description = "Syllable and Word generation library written fully in Rust"

[lib]
name = "try_words"
path = "src/lib.rs"


[dependencies]
csv = "1.1.3"